# Generated by Django 3.1.3 on 2023-04-09 22:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0002_auto_20230409_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientaccount',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='dd-mm-yyyy'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientaccount',
            name='gender',
            field=models.CharField(default='f', max_length=10),
            preserve_default=False,
        ),
    ]
